project_id = "zfjvflqzbahzgwvfqmph"

[functions.create-course-checkout]
verify_jwt = false

[functions.verify-course-payment]
verify_jwt = false

[functions.create-subscription]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false
